package com.xabe.mybatis.mapper;

import org.apache.ibatis.jdbc.SQL;

public class EventSqlBuilder {

  public static String dropTableSql() {
    return "DROP TABLE IF EXISTS t_${name}";
  }

  public static String createTableIfNotExistSql() {
    return """
            CREATE TABLE IF NOT EXISTS t_${name} \
            ( \
              ID varchar(255) NOT NULL, \
              NAME varchar(255) DEFAULT NULL, \
              BODY varchar(255) DEFAULT NULL, \
              CREATED_AT timestamp NULL DEFAULT NULL, \
              SENT_AT timestamp NULL DEFAULT NULL, \
              PRIMARY KEY (id) \
            )ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='this table is generated by java code.'
        """;
  }

  public static String buildGetNonSentEventsSql() {
    return new SQL() {
      {
        this.SELECT("ID", "CREATED_AT", "NAME", "BODY");
        this.FROM("t_event");
        this.WHERE("SENT_AT is null");
      }
    }.toString();
  }

  public static String buildCreateEventSql() {
    return new SQL() {
      {
        this.INSERT_INTO("t_event");
        this.VALUES("ID", "#{event.id}");
        this.VALUES("CREATED_AT", "#{event.createdAt}");
        this.VALUES("NAME", "#{event.name}");
        this.VALUES("BODY", "#{event.body}");
      }
    }.toString();
  }

  public static String buildMarkEventAsSentSql() {
    return new SQL() {
      {
        this.UPDATE("t_event");
        this.SET("SENT_AT = #{sentAt}");
        this.WHERE("ID = #{eventId}");
      }
    }.toString();
  }

}
